### ISSUE TITLE
WireFilter offset

### ISSUE THREAD

**Issue by macdroid53** [mwganson/wirefilter#3]
I can't seem to get an offset other than arcs...(same file using selected edges filtered
![Snip macro screenshot-486ba4](https://user-images.githubusercontent.com/6831752/147413968-01bcd5ca-da83-413e-a02a-fc932c12b2e2.png)
)

` File "/home/mac/SharedData/FC_common/wirefilter.py", line 309, in execute
    shape = self.executeUseSelectedEdges(fp, shape)
  File "/home/mac/SharedData/FC_common/wirefilter.py", line 173, in executeUseSelectedEdges
    wire = self.offset(fp,wire)
  File "/home/mac/SharedData/FC_common/wirefilter.py", line 120, in offset
    return(shp.makeOffset2D(fp.Offset,join,fp.OffsetFill,fp.OffsetOpenResult,fp.OffsetIntersection))
<class 'Base.FreeCADError'>: makeOffset2D: result of offsetting is null!
`
![WireFilterOffsetSettings](https://user-images.githubusercontent.com/6831752/147414031-0a1dedc4-1a82-4739-b144-cdbc41fa7dfa.png)

Is this just standard limitation of the 2D offset with splines?

**Comment by mwganson** [comment]
Yes, probably just a limitation of the 2D offset.  For comparison you may try the same object in Part workbench with the 2d offset tool.  I have found the arcs mode to be more robust than the others.

**Comment by macdroid53** [comment]
Sigh, FreeCAD and offsets.
